package com.example.jira;

import java.lang.reflect.Field;

/**
 * Entity ids are generated by the database, so there is no setter for them. Unit tests that never
 * touch a database still need an item and a list to have distinguishable ids, and this is the one
 * place that reaches in to set them.
 */
public final class TestEntities {

    private TestEntities() {}

    public static <T> T withField(T entity, String fieldName, Object value) {
        try {
            Field field = entity.getClass().getDeclaredField(fieldName);
            field.setAccessible(true);
            field.set(entity, value);
            return entity;
        } catch (ReflectiveOperationException exception) {
            throw new IllegalStateException("could not set " + fieldName + " on " + entity.getClass(), exception);
        }
    }
}
